name       : lector
version    : 0.5.1
release    : 5
source     :
    - https://github.com/BasioMeusPuga/Lector/archive/0.5.1.tar.gz : f35dc56a870f02b3eeb95d697ecd1e4784a7696f831fdfd8eb5dc935da622be6
license    : GPL-3.0-or-later
component  : office.viewers
summary    : Qt based ebook reader
description: |
    Qt based ebook reader
builddeps  :
    - python3-qt5
rundeps    :
    - poppler-qt5
    - python-beautifulsoup4
    - python-lxml
    - python-xmltodict
build      : |
    %python3_setup
install    : |
    %python3_install
