name       : lector
version    : 0.4
release    : 1
source     :
    -  https://github.com/BasioMeusPuga/Lector/archive/0.4.tar.gz : c8deefc20fb3da98a327a893ce281e1efe5ee0c0a306d8cd19b44fd2e526649a
license    : GPL-3.0-or-later
component  : office.viewers
summary    : Qt based ebook reader
description: |
    Qt based ebook reader
rundeps  :
    - poppler-qt5
    - python-beautifulsoup4
    - python3-qt5
build      : |
    %python3_setup
install    : |
    %python3_install
